general: 
  dataset_name: organamnist
  num_classes: 11
datasets:
  imbalance_ratio: 10
  head: 3
  medium: 6
  tail: 11
  teacher_class: [6, 7, 8, 9, 10]
  img_path: '/public/home/chenweilin/classImbalace-compareMethod/dataset/medmnist_images/organamnist_224/'
  train:
    np_path: '/public/home/chenweilin/classImbalace-compareMethod/numpy/medmnist/organamnist_train.npy'
    dict_path: '/public/home/chenweilin/classImbalace-compareMethod/numpy/medmnist/organamnist_dic.npy'
  val:
    np_path: '/public/home/chenweilin/classImbalace-compareMethod/numpy/medmnist/organamnist_val.npy'
    dict_path: '/public/home/chenweilin/classImbalace-compareMethod/numpy/medmnist/organamnist_dic.npy'
  test:
    np_path: '/public/home/chenweilin/classImbalace-compareMethod/numpy/medmnist/organamnist_test.npy'
    dict_path: '/public/home/chenweilin/classImbalace-compareMethod/numpy/medmnist/organamnist_dic.npy'
  transforms:
    train: 'strong'
    val_test: 'normal'