general: 
  dataset_name: bloodmnist
  num_classes: 8
datasets:
  imbalance_ratio: 10
  head: 3
  medium: 5
  tail: 8
  teacher_class: [5, 6, 7]
  img_path: '/public/home/chenweilin/classImbalace-compareMethod/dataset/medmnist_images/bloodmnist_224/'
  train:
    np_path: '/public/home/chenweilin/classImbalace-compareMethod/numpy/medmnist/bloodmnist_train.npy'
    dict_path: '//public/home/chenweilin/classImbalace-compareMethod/numpy/medmnist/bloodmnist_dic.npy'
  val:
    np_path: '/public/home/chenweilin/classImbalace-compareMethod/numpy/medmnist/bloodmnist_val.npy'
    dict_path: '/public/home/chenweilin/classImbalace-compareMethod/numpy/medmnist/bloodmnist_dic.npy'
  test:
    np_path: '/public/home/chenweilin/classImbalace-compareMethod/numpy/medmnist/bloodmnist_test.npy'
    dict_path: '/public/home/chenweilin/classImbalace-compareMethod/numpy/medmnist/bloodmnist_dic.npy'
  transforms:
    train: 'strong'
    val_test: 'normal'